name: grammar or typographical error
description: "the maintainer is not a native english speaker. reports are welcome."
title: "[typo]: "
labels: [typo]
assignees:
  - zaboal
body:
  - type: input
    attributes:
      label: where's the typo?
      placeholder: readme
  - type: textarea
    attributes:
      label: how must it be?
      description: write your version of the sentences and optionally explain them.
